#SPDX-License-Identifier: MIT-0
---
- include_tasks: setup-debian-13.yml
  when:
    - ansible_facts.distribution == 'Debian'
    - ansible_facts.distribution_major_version | int == 13

- include_tasks: setup-fedora-42.yml
  when:
    - ansible_facts.distribution == 'Fedora'
    - ansible_facts.distribution_major_version | int == 42
