- name: Ensure {{ debian_keyrings_dir }} is created
  ansible.builtin.file:
    path: "{{ debian_keyrings_dir }}"
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Import tailscale apt key
  ansible.builtin.get_url:
    url: "{{ debian_trixie_apt_key_url }}"
    dest: "{{ debian_trixie_apt_key_dest }}"
    mode: "0644"

- name: Add tailscale apt repo list
  ansible.builtin.get_url:
    url: "{{ debian_trixie_apt_repo_list_url }}"
    dest: "{{ debian_trixie_apt_repo_list_dest }}"
    mode: "0644"

- name: Install tailscale
  ansible.builtin.apt:
    name: 
      - tailscale
      - tailscale-archive-keyring
    state: present
    update_cache: true
